---
- hosts: all
  remote_user: ansible

  tasks:
  - name: Remove the 'bootstrap' user
    user:
      name: bootstrap
      state: absent
      remove: yes

  - name: Manage Laptop Lid
    include_tasks: manage_laptop_lid_tasks.yml

  - name: Install all the Concourse Things
    include_tasks: concourse_tasks.yml
