---
- hosts: all
  remote_user: ansible

  tasks:
  - name: Remove the 'bootstrap' user
    user:
      name: bootstrap
      state: absent
      remove: yes

  # https://itsfoss.com/disable-ipv6-ubuntu-linux/
  - sysctl:
      name: net.ipv6.conf.all.disable_ipv6
      value: '1'
      state: present

  - sysctl:
      name: net.ipv6.conf.default.disable_ipv6
      value: '1'
      state: present

  - sysctl:
      name: net.ipv6.conf.lo.disable_ipv6
      value: '1'
      state: present
