# TLS info came from:
# https://www.papertrail.com/help/encrypting-remote-syslog-with-tls-ssl/
- name: Add Bullseye Backports repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/bullsey-backports.list
    content: |
      deb http://deb.debian.org/debian bullseye-backports main contrib non-free
      deb-src http://deb.debian.org/debian bullseye-backports main contrib non-free


- name: Update Apt cache
  ansible.builtin.apt:
    update_cache: true


- name: Ensure required packages are installed
  apt:
    pkg:
    - rsyslog
    - rsyslog-gnutls
    state: latest
    default_release: bullseye-backports
  notify:
    - Restart rsyslog


- name: Add papertrail CA
  become: true
  get_url:
    dest: /etc/papertrail-bundle.pem
    owner: root
    group: admin
    mode: '0664'
    url: https://papertrailapp.com/tools/papertrail-bundle.pem


- name: Add Papertrail forwarding configuration
  become: true
  copy:
    dest: /etc/rsyslog.d/papertrail.conf
    content: |
      $ActionSendStreamDriverPermittedPeer *.papertrailapp.com

      *.* action(type="omfwd"
                 target="{{ secrets.rsyslog_forwarding_target }}"
                 port="{{ secrets.rsyslog_forwarding_port }}"
                 StreamDriver="gtls"
                 StreamDriverMode="1"
                 StreamDriverAuthMode="anon"
                 StreamDriverCAFile="/etc/papertrail-bundle.pem"
                 queue.spoolDirectory="/var/spool/rsyslog"
                 queue.filename="papertrail"
                 queue.maxdiskspace="75m"
                 queue.type="LinkedList"
                 queue.saveonshutdown="on"
                 protocol="tcp")
    owner: root
    group: admin
    mode: '0640'
  notify:
    - Restart rsyslog


- name: Add Betterstack forwarding configuration
  become: true
  copy:
    dest: /etc/rsyslog.d/betterstack.conf
    content: |
      template(name="LogtailFormat" type="list") {
       constant(value="<")
       property(name="pri")
       constant(value=">")
       constant(value="1")
       constant(value=" ")
       property(name="timestamp" dateFormat="rfc3339")
       constant(value=" ")
       property(name="hostname")
       constant(value=" ")
       property(name="app-name")
       constant(value=" ")
       property(name="procid")
       constant(value=" ")
       property(name="msgid")
       constant(value=" ")
       property(name="structured-data" regex.expression="[^-]" regex.nomatchmode="BLANK" regex.submatch="0")
       constant(value="[logtail@11993 source_token=\"{{ secrets.rsyslog_source_token }}\"]")
       constant(value=" ")
       property(name="msg" droplastlf="on")
      }

      action(
       type="omfwd"
       protocol="tcp"
       target="in.logs.betterstack.com"
       port="6514"
       template="LogtailFormat"
       TCP_Framing="octet-counted"
       StreamDriver="gtls"
       StreamDriverMode="1"
       StreamDriverAuthMode="x509/name"
       StreamDriverPermittedPeers="*.logs.betterstack.com"
       StreamDriverCAFile="/etc/ssl/certs/ca-certificates.crt"
       queue.spoolDirectory="/var/spool/rsyslog"
       queue.filename="betterstack"
       queue.maxdiskspace="75m"
       queue.type="LinkedList"
       queue.saveonshutdown="on"
      )

    owner: root
    group: admin
    mode: '0640'
  notify:
    - Restart rsyslog
