# TLS info came from:
# https://www.papertrail.com/help/encrypting-remote-syslog-with-tls-ssl/
- name: Ensure required packages are installed
  apt:
    name: rsyslog-gnutls

- name: Add papertrail CA
  become: true
  get_url:
    dest: /etc/papertrail-bundle.pem
    owner: root
    group: admin
    mode: '0664'
    url: https://papertrailapp.com/tools/papertrail-bundle.pem


- name: Add Papertrail forwarding configuration
  become: true
  copy:
    dest: /etc/rsyslog.d/papertrail.conf
    content: |
      global(DefaultNetstreamDriverCAFile="/etc/papertrail-bundle.pem")
      $ActionSendStreamDriverPermittedPeer *.papertrailapp.com

      *.* action(type="omfwd"
                 target="{{ secrets.rsyslog_forwarding_target }}"
                 port="{{ secrets.rsyslog_forwarding_port }}"
                 StreamDriver="gtls"
                 StreamDriverMode="1"
                 StreamDriverAuthMode="x509/name"
                 protocol="tcp")
    owner: root
    group: admin
    mode: '0640'
  notify:
    - Restart rsyslog
