- name: Install certbot package
  ansible.builtin.apt:
    name: certbot

# I've elected to disable automated renewals. This requires different
# logic for renewing a certificate than creating new a new one. Rather
# than renew certificates, I use the e-mail notification from letsencrypt
# as cue to repave the PI. This ensures that the bootstrapping process
# just works.
#
# ref: https://eff-certbot.readthedocs.io/en/stable/using.html#automated-renewals
- name: Disable certbot.timer
  ansible.builtin.service:
    name: certbot.timer
    enabled: false
    state: stopped


# Nginx needs to be stopped so certbot --standalone can bind to port 80 to
# fulfill the ACME challenges. This only needs to happen when the required
# certificates don't exist, but haven't implemented logic for that yet.
# The nginx_tasks.yml will ensure that the service is started eventually.
- name: Ensure nginx is stopped before certbot interactions
  ansible.builtin.service:
    name: nginx
    state: stopped
  # Ignoring errors handles the first exeuction problem where these tasks
  # run before nginx is installed.
  ignore_errors: true


# TODO: inject fqdns from the playbook
- name: Acquire certificates
  # This breaks when making it a fulle qualified module name
  command: |
    certbot certonly --standalone --non-interactive --agree-tos
    -d {{ item.fqdn }} \
    -m {{ item.email }}
  args:
    creates: /etc/letsencrypt/live/{{ item.fqdn }}/fullchain.pem
  loop:
    - fqdn: www.goodenoughmoney.com
      email: "scottmuc@gmail.com"
    - fqdn: home.scottmuc.com
      email: "scottmuc@gmail.com"
