- name: Delete old Grafana Apt Repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: absent

# Introduce the new repository
# https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/#repository-migration-november-8th-2022
- name: Install Grafana Apt Keys
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present


- name: Add Grafana Apt Repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present


- name: Install grafana package
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: true
  notify:
    - Systemd reload


- name: Install grafana configuration
  ansible.builtin.copy:
    src: root/etc/grafana/grafana.ini
    dest: /etc/grafana/grafana.ini
    owner: root
    group: admin
    mode: '0664'
  notify:
    - Restart grafana


- name: Ensure grafana is running
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true
