---
- hosts: all
  remote_user: ansible
  become: yes

  tasks:
  - name: Remove the 'pi' user
    user:
      name: pi
      state: absent
      remove: yes

  - name: Disable IPV6
    include_tasks: disable_ipv6_tasks.yml

  - name: Install DNS stuff
    include_tasks: unbound_tasks.yml

  - name: Install nginx and configure websites
    include_tasks: nginx_tasks.yml

  - name: Setup USB Drive
    include_tasks: usb_drive_tasks.yml

  - name: Setup Samba
    include_tasks: samba_tasks.yml

  - name: Configure static IP
    include_tasks: networking_tasks.yml

  - name: Setup kea dhcpd
    include_tasks: dhcpd_tasks.yml

  handlers:
  - name: Restart unbound
    ansible.builtin.service:
      name: unbound
      state: restarted


  - name: Restart kea-dhcp4-server
    ansible.builtin.service:
      name: kea-dhcp4-server
      state: restarted
