---
# TODO: use well defined inventory file and specify host
- hosts: all
  remote_user: ansible
  # TODO: eliminate the global priv elevation
  become: true
  # Are these global? Yes, they are.
  vars:
    prometheus_version: "2.39.1"
    navidrome_version: "0.48.0"
    node_exporter_version: "1.4.0"
    sysctls:
      # https://linuxhint.com/understanding_vm_swappiness/
      - name: vm.swappiness
        value: '1'
      # Disable IPv6
      - name: net.ipv6.conf.all.disable_ipv6
        value: '1'
      - name: net.ipv6.conf.default.disable_ipv6
        value: '1'
      - name: net.ipv6.conf.lo.disable_ipv6
        value: '1'


  roles:
  - logging
  - dnsresolver
  - staticip
  - certificates


  tasks:
  # If this fails, it's likely due to user level systemd services running. A
  # reboot will resolve it... will look into more elegant ways later.
  - name: Delete the 'pi' bootstrap user
    ansible.builtin.user:
      name: pi
      state: absent
      remove: true

  - name: Configure sysctls
    ansible.posix.sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      state: present
    tags: [ sysctls ]
    loop: "{{ sysctls }}"

  - name: Install and configure nginx
    tags: nginx
    include_tasks:
      file: nginx_tasks.yml
      apply:
        tags: nginx

  - name: Setup nginx vhosts
    include_tasks: vhost_tasks.yml

  - name: Setup USB Drive
    include_tasks: usb_drive_tasks.yml

  - name: Setup Samba
    include_tasks: samba_tasks.yml

  - name: Install dnsmasq
    include_tasks: dhcpd_tasks.yml

  - name: Install navidrome
    tags: navidrome
    include_tasks:
      file: navidrome_tasks.yml
      apply:
        tags: navidrome

  - name: Install prometheus
    tags: prometheus
    include_tasks:
      file: prometheus_tasks.yml
      apply:
        tags: prometheus

  - name: Install node exporter
    include_tasks: node_exporter_tasks.yml

  - name: Install grafana
    tags: grafana
    include_tasks:
      file: grafana_tasks.yml
      apply:
        tags: grafana


  handlers:
    # It's important that Systemd reload is defined first here
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html#controlling-when-handlers-run
    #
    # This might not be necessary though... still need to think this through
    - name: Systemd reload
      ansible.builtin.systemd:
        daemon_reload: true


    - name: Restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted


    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted


    - name: Restart smbd
      ansible.builtin.service:
        name: smbd
        state: restarted


    - name: Restart navidrome
      ansible.builtin.service:
        name: navidrome
        state: restarted


    - name: Restart prometheus
      ansible.builtin.service:
        name: prometheus
        state: restarted


    - name: Restart node_exporter
      ansible.builtin.service:
        name: node_exporter
        state: restarted


    - name: Restart grafana
      ansible.builtin.service:
        name: grafana-server
        state: restarted
