---
- hosts: all
  remote_user: ansible
  become: yes

  tasks:
  - name: Configure log forwarding
    include_tasks: rsyslog_tasks.yml

  - name: Disable the 'pi' user
    user:
      name: pi
        #state: absent
        #      remove: yes
      shell: /sbin/nologin

  - name: Disable IPV6
    include_tasks: disable_ipv6_tasks.yml

  - name: Install DNS stuff
    include_tasks: unbound_tasks.yml

  - name: Install nginx and configure websites
    include_tasks: nginx_tasks.yml

  - name: Setup USB Drive
    include_tasks: usb_drive_tasks.yml

  - name: Setup Samba
    include_tasks: samba_tasks.yml

  - name: Configure static IP
    include_tasks: networking_tasks.yml

  - name: Setup kea dhcpd
    include_tasks: dhcpd_tasks.yml

  - name: Install navidrome
    include_tasks: navidrome_tasks.yml

  - name: Install prometheus
    include_tasks: prometheus_tasks.yml

  handlers:
  # It's important that Systemd reload is defined first here
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html#controlling-when-handlers-run
  #
  # This might not be necessary though... still need to think this through
  - name: Systemd reload
    ansible.builtin.systemd:
      daemon_reload: Yes


  - name: Restart unbound
    ansible.builtin.service:
      name: unbound
      state: restarted


  - name: Restart kea-dhcp4-server
    ansible.builtin.service:
      name: kea-dhcp4-server
      state: restarted


  - name: Restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted


  - name: Restart smbd
    ansible.builtin.service:
      name: smbd
      state: restarted


  - name: Restart navidrome
    ansible.builtin.service:
      name: navidrome
      state: restarted


  - name: Restart prometheus
    ansible.builtin.service:
      name: prometheus
      state: restarted


  - name: Restart rsyslog
    ansible.builtin.service:
      name: rsyslog
      state: restarted
