---
- hosts: all
  remote_user: ansible

  tasks:
  - name: Disable IPV6
    include_tasks: disable_ipv6_tasks.yml

  - name: Install DNS stuff
    include_tasks: unbound_tasks.yml

  - name: Install nginx and configure websites
    include_tasks: nginx_tasks.yml

  - name: Setup USB Drive
    include_tasks: usb_drive_tasks.yml

  - name: Configure static IP
    include_tasks: networking_tasks.yml
