---
# TODO: use well defined inventory file and specify host
- hosts: all
  remote_user: ansible
  # TODO: eliminate the global priv elevation
  become: true
  # Are these global? Yes, they are.
  vars:
    prometheus_version: "2.37.1"


  roles:
  - logging
  - dnsresolver


  tasks:
    # TODO: delete user (need to sort out systemd stuff)
  - name: Disable the 'pi' user
    user:
      name: pi
      shell: /sbin/nologin

    # https://linuxhint.com/understanding_vm_swappiness/
  - name: Configure swappiness to a minimum
    ansible.posix.sysctl:
      name: vm.swappiness
      value: '1'
      state: present

  - name: Disable IPV6
    include_tasks: disable_ipv6_tasks.yml

  - name: Install nginx and configure websites
    include_tasks: nginx_tasks.yml

  - name: Setup USB Drive
    include_tasks: usb_drive_tasks.yml

  - name: Setup Samba
    include_tasks: samba_tasks.yml

  - name: Configure static IP
    include_tasks: networking_tasks.yml

  - name: Install dnsmasq
    include_tasks: dhcpd_tasks.yml

  - name: Install navidrome
    tags: navidrome
    include_tasks:
      file: navidrome_tasks.yml
      apply:
        tags: navidrome

  - name: Install prometheus
    tags: prometheus
    include_tasks:
      file: prometheus_tasks.yml
      apply:
        tags: prometheus

  - name: Install node exporter
    include_tasks: node_exporter_tasks.yml

  - name: Install grafana
    include_tasks: grafana_tasks.yml


  handlers:
    # It's important that Systemd reload is defined first here
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html#controlling-when-handlers-run
    #
    # This might not be necessary though... still need to think this through
    - name: Systemd reload
      ansible.builtin.systemd:
        daemon_reload: true


    - name: Restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted


    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted


    - name: Restart smbd
      ansible.builtin.service:
        name: smbd
        state: restarted


    - name: Restart navidrome
      ansible.builtin.service:
        name: navidrome
        state: restarted


    - name: Restart prometheus
      ansible.builtin.service:
        name: prometheus
        state: restarted


    - name: Restart node_exporter
      ansible.builtin.service:
        name: node_exporter
        state: restarted


    - name: Restart grafana
      ansible.builtin.service:
        name: grafana-server
        state: restarted
