- name: Install samba package
  ansible.builtin.apt:
    name: samba


- name: Creating Samba specific user
  ansible.builtin.user:
    name: smbrw
    comment: Samba RW
    create_home: true
    shell: /usr/sbin/nologin


- name: Add share information
  ansible.builtin.blockinfile:
    dest: /etc/samba/smb.conf
    block: |
      [fileserver]
        path = /mnt/usb
        browseable = yes
        read only = no
        guest ok = no
        valid users = smbrw
    backup: true
  notify:
    - Restart smbd


- name: Ensure smbd is running
  ansible.builtin.service:
    name: smbd
    state: started
    enabled: true


# Manually create pi user `sudo smbpasswd -a smbrw`
